// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfUoR_DDJ6xLa_MvRfX8QOSFqwmWrpKZo',
    appId: '1:521886883437:web:788bf668b0a17dd23ae964',
    messagingSenderId: '521886883437',
    projectId: 'care-net-bb873',
    authDomain: 'care-net-bb873.firebaseapp.com',
    storageBucket: 'care-net-bb873.appspot.com',
    measurementId: 'G-HK0DWH5RE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3wjEOKedA-7UsTwr7npkbDFdKEa2n47c',
    appId: '1:521886883437:android:f74e281aa07a256b3ae964',
    messagingSenderId: '521886883437',
    projectId: 'care-net-bb873',
    storageBucket: 'care-net-bb873.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtFFc2hJvTvH0cGw0Iln4fMX1qkUFZ1JE',
    appId: '1:521886883437:ios:6115c355dc6805ce3ae964',
    messagingSenderId: '521886883437',
    projectId: 'care-net-bb873',
    storageBucket: 'care-net-bb873.appspot.com',
    iosBundleId: 'com.example.carenet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtFFc2hJvTvH0cGw0Iln4fMX1qkUFZ1JE',
    appId: '1:521886883437:ios:3eaa6b4f26b613c73ae964',
    messagingSenderId: '521886883437',
    projectId: 'care-net-bb873',
    storageBucket: 'care-net-bb873.appspot.com',
    iosBundleId: 'com.example.carenet.RunnerTests',
  );
}
